### PR TITLE
Browser widget

### PR DESCRIPTION
**Pull request by lepmik**
Browser for selecting actions for analysis, browsing attributes, modules, templates, and entities

Test it out in a `jupyter notebook` with
```python
b = Browser('/path/to/project')
b.display()
```

It is not tested much and probably have some bugs, but I think it is ready to see the light of day (at least in this PR)

### CODE REVIEW

**Comment by lepmik** [comment]
TODO

- [ ] Searchbox for actions in  'Attributes', 'Modules', 'Templates', 'Entities'

**Comment by dragly** [comment]
I love it! As mentioned offline, let's see if we can make this so that

```project.actions```

shows a simple browser for selecting actions and

```project.actions['my_action'].modules```

shows a simple browser for the modules of an action.

Basically making it modular (which it seems you already did by separating everything into classes).

**Comment by lepmik** [comment]
project, actions, entities, modules, messages, and templates now have their own representational view in jupyter with ipywidgets. In addition `MapManager` has tab completions i.e. `project.actions[<tab>` gives a list of possible keys (!)  Ipython is pretty awesome!

**Comment by lepmik** [comment]
I think this is ready to merge @dragly

**Pull request merged**
